cat <<EOF | oc apply -f -
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: KAFKA_BROKERCONNECT
              value: 'my-cluster-kafka-bootstrap:9092'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  selector:
    app: kafdrop
  ports:
     - name: 9000-tcp
       protocol: TCP
       port: 9000
       targetPort: 9000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafdrop
spec:
  path: /
  to:
    kind: Service
    name: kafdrop
  port:
    targetPort: 9000-tcp
EOF


