apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
  namespace: my-app-project
spec:
  whitelist: .*
  producer:
    bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
  consumer:
    bootstrapServers: 'target-cluster-kafka-bootstrap:9092'
    groupId: my-source-group-id
  version: 2.6.0
  replicas: 1

